### ISSUE TITLE
LinkTokenGetRequest api call not working in versions >=19.0.0

### ISSUE THREAD

**Issue by yoheioka** [plaid/plaid-python#532]
```
client = plaid_api.PlaidApi(plaid.ApiClient(configuration))
api_request = LinkTokenGetRequest(link_token=link_token_id)
response = client.link_token_get(api_request)
```
results in 
```
  File "/Users/user/.pyenv/versions/3.11/envs/pyenv-env/lib/python3.12/site-packages/plaid/model_utils.py", line 1424, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11/envs/pyenv-env/lib/python3.12/site-packages/plaid/model_utils.py", line 1338, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11/envs/pyenv-env/lib/python3.12/site-packages/plaid/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11/envs/pyenv-env/lib/python3.12/site-packages/plaid/model_utils.py", line 371, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pyenv/versions/3.11/envs/pyenv-env/lib/python3.12/site-packages/plaid/model_utils.py", line 48, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LinkEventMetadata._from_openapi_data() missing 1 required positional argument: 'request_id
```

Latest working version is `18.4.0`

**Comment by phoenixy1** [comment]
Thank you for the report. I've confirmed that this is an issue and we'll make sure it's fixed in the next version of the client library. If this is a blocker for you, let me know.

**Comment by yoheioka** [comment]
@phoenixy1 
We can wait until the next version of the client. Thanks!
